# Generated by Django 5.0.1 on 2024-01-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='user_default.png', upload_to='profile_pics'),
        ),
    ]
