# Generated by Django 4.2.6 on 2024-01-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0006_alter_purchaseorder_ord_date_posted_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='ORD_PRICE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
