# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\pythonproject\LogginIn.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Doc_ui import Ui_Doctors
import testimage_rc

class Ui_Login(object):
        
    def openWindow(self):
        username = self.lineEdit.text()
        password = self.lineEdit_2.text()
        if username == "admin" and password == "pass":
            self.window = QtWidgets.QMainWindow()
            self.ui = Ui_Doctors()  
            self.ui.setupUi(self.window)
            MainWindow.hide()
            self.window.show()
        else:
            QtWidgets.QMessageBox.warning(
                self.centralwidget,
                "Invalid Credentials",
                "Invalid username or password. Please try again."
            )    
            
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(799, 570)
        Login.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 40, 461, 71))
        self.label.setStyleSheet("color:rgb(85, 85, 255);\n"
"font: 8pt \"MS Reference Sans Serif\"; font-size: 40px;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 280, 111, 21))
        self.label_2.setStyleSheet("font-size: 20px")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(460, 280, 281, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 340, 111, 31))
        self.label_3.setStyleSheet("font-size: 20px")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(460, 340, 281, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(540, 390, 101, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.openWindow)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 110, 261, 71))
        self.label_4.setStyleSheet("color:rgb(85, 85, 255);\n"
"font: 8pt \"MS Reference Sans Serif\"; font-size: 40px;")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 301, 251))
        self.label_5.setStyleSheet("background-image:url(:/Image/images/undraw_medicine_b1ol.png)")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/Image/images/undraw_medicine_b1ol.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "CLINIC APPOINTMENT"))
        self.label_2.setText(_translate("Login", "Username:"))
        self.label_3.setText(_translate("Login", "Password:"))
        self.pushButton.setText(_translate("Login", "LOGIN"))
        self.label_4.setText(_translate("Login", "SCHEDULER"))
        


if __name__ == '__main__':
        import sys
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_Login()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())

