# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\pythonproject\Table.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import psycopg2


class Ui_View(object):
    def __init__(self):
        # Create a connection to the database
        self.connection = psycopg2.connect(
            host='localhost',
            port='5432',
            database='mydb',
            user='postgres',
            password='cheesecake'
        )
        self.cursor = self.connection.cursor()

    def setupUi(self, View):
        View.setObjectName("View")
        View.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(View)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(50, 50, 700, 500))
        self.tableView.setObjectName("tableView")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(360, 560, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.loadAppointments)
        self.backButton = QtWidgets.QPushButton(self.centralwidget)
        self.backButton.setGeometry(QtCore.QRect(470, 560, 75, 23))
        self.backButton.setObjectName("backButton")
        self.backButton.setText("Back")
        self.backButton.clicked.connect(self.goBack)
        self.backButton.clicked.connect(View.close)
        View.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(View)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        View.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(View)
        self.statusbar.setObjectName("statusbar")
        View.setStatusBar(self.statusbar)

        self.retranslateUi(View)
        QtCore.QMetaObject.connectSlotsByName(View)

    def retranslateUi(self, View):
        _translate = QtCore.QCoreApplication.translate
        View.setWindowTitle(_translate("View", "View Appointments"))
        self.pushButton.setText(_translate("View", "Load"))
        
    def goBack(self):
        from App_ui import Ui_Appointment
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Appointment()
        self.ui.setupUi(self.window)
        self.window.show()   
        
    def loadAppointments(self):
        self.cursor.execute("SELECT pat_id, pat_fname, pat_lname, pat_age, pat_gender, pat_contacts, pat_date, pat_time FROM PATIENT")
        appointments = self.cursor.fetchall()
        table_model = QtGui.QStandardItemModel()
        table_model.setColumnCount(8)
        table_model.setHorizontalHeaderLabels(['ID', 'First Name', 'Last Name', 'Age', 'Gender', 'Contacts', 'Date', 'Time'])

        for row, appointment in enumerate(appointments):
            for column, data in enumerate(appointment):
                item = QtGui.QStandardItem(str(data))
                table_model.setItem(row, column, item)

        self.tableView.setModel(table_model)


if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_View()
    ui.setupUi(MainWindow)
    MainWindow.show()

    ui.loadAppointments()

    sys.exit(app.exec_())
