# Generated by Django 4.2.6 on 2024-01-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
    ]
