# Generated by Django 4.2.6 on 2024-01-06 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ms18', '0005_rename_date_posted_product_prod_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='ORD_DATE_POSTED',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CART_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CART_QUANTITY', models.IntegerField(default=0)),
                ('CART_DATE_ADDED', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms18.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
