# Generated by Django 4.2.6 on 2024-01-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0007_purchaseorder_ord_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SUPPLIER_ID', models.AutoField(primary_key=True, serialize=False)),
                ('SUPPLIER_NAME', models.CharField(max_length=100)),
                ('SUPPLIER_ADDRESS', models.TextField()),
                ('SUPPLIER_PHONE', models.CharField(max_length=20)),
            ],
        ),
    ]
