# Generated by Django 5.0.1 on 2024-01-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0009_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PROD_DESCRIPTION',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='ORD_DESCRIPTION',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SUPPLIER_ADDRESS',
            field=models.CharField(max_length=200),
        ),
    ]
