# Generated by Django 5.0.1 on 2024-01-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0010_alter_product_prod_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PROD_DATE_POSTED',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='SUPPLIER_PHONE',
            field=models.CharField(max_length=12),
        ),
    ]
