# Generated by Django 5.0.1 on 2024-01-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0011_remove_product_prod_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('REQ_ID', models.AutoField(primary_key=True, serialize=False)),
                ('REQ_EMPLOYEE', models.CharField(max_length=100)),
                ('REQ_STATUS', models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='PROD_STATUS',
            field=models.CharField(default='Average', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
