# Generated by Django 5.0.1 on 2024-01-12 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0012_requisition_product_prod_status_purchaseorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PROD_STATUS',
        ),
        migrations.CreateModel(
            name='RequestedProduct',
            fields=[
                ('REQ_PROD_ID', models.AutoField(primary_key=True, serialize=False)),
                ('REQ_PROD_NAME', models.CharField(max_length=100)),
                ('REQ_PROD_QUANTITY', models.IntegerField(default=0)),
                ('PROD_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms18.product')),
                ('REQ_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms18.requisition')),
            ],
        ),
    ]
