# Generated by Django 5.0.1 on 2024-01-12 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0013_remove_product_prod_status_requestedproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedproduct',
            old_name='PROD_ID',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='REQ_ID',
        ),
        migrations.RemoveField(
            model_name='requestedproduct',
            name='REQ_PROD_NAME',
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='REQ_PROD_DATE_ADDED',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
