# Generated by Django 5.0.1 on 2024-01-13 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0016_rename_req_employee_requisition_req_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='requested_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ms18.requestedproduct'),
        ),
    ]
