# Generated by Django 5.0.1 on 2024-01-13 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0017_requisition_requested_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='requested_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ms18.requestedproduct'),
        ),
    ]
