# Generated by Django 5.0.1 on 2024-01-13 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0018_alter_requisition_requested_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='REQ_STATUS',
        ),
    ]
