# Generated by Django 5.0.1 on 2024-01-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0019_remove_requisition_req_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
