# Generated by Django 5.0.1 on 2024-01-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0021_rename_product_requestedproduct_prod_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestedproduct',
            old_name='PROD_ID',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='requisition',
            old_name='REQUESTED_PRODUCT_ID',
            new_name='RequestedProduct',
        ),
    ]
