# Generated by Django 5.0.1 on 2024-01-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0022_rename_prod_id_requestedproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='RequestedProduct',
        ),
        migrations.AddField(
            model_name='requisition',
            name='requested_products',
            field=models.ManyToManyField(to='ms18.requestedproduct'),
        ),
    ]
