# Generated by Django 5.0.1 on 2024-01-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0024_requisition_req_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='requested_products',
        ),
        migrations.AddField(
            model_name='requestedproduct',
            name='Requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ms18.requisition'),
        ),
    ]
