# Generated by Django 5.0.1 on 2024-01-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0025_remove_requisition_requested_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='SUPPLIER_ID',
            new_name='Supplier',
        ),
    ]
