# Generated by Django 5.0.1 on 2024-01-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0026_rename_supplier_id_requisition_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestedproduct',
            name='Requisition',
        ),
        migrations.AddField(
            model_name='requisition',
            name='requested_products',
            field=models.ManyToManyField(to='ms18.requestedproduct'),
        ),
    ]
