# Generated by Django 5.0.1 on 2024-01-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0027_remove_requestedproduct_requisition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='Supplier',
            new_name='supplier',
        ),
    ]
