# Generated by Django 5.0.1 on 2024-01-15 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ms18', '0028_rename_supplier_requisition_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='requested_products',
        ),
        migrations.AddField(
            model_name='requisition',
            name='requestedproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ms18.requestedproduct'),
        ),
    ]
